# PUMP IDS
PUMP_CONSTANT_TANK = "pump_constant_tank"
PUMP_MEASURING_TANK = "pump_measuring_tank"

# VALVE IDS
MEASURING_DRAIN_VALVE = "measuring_drain_valve"
MEASURING_BYPASS_VALVE = "measuring_bypass_valve"
MEASURING_TANK_SWITCH = "measuring_tank_switch"

# TANK IDS
STOCK_TANK = "stock_tank"
CONSTANT_TANK = "constant_tank"
MEASURING_TANK = "measuring_tank"

# LEVEL SENSOR IDS
LEVEL_MEASURING_TOP = "level_measuring_top"
LEVEL_MEASURING_BOTTOM = "level_measuring_bottom"
LEVEL_CONSTANT_TOP = "level_constant_top"
LEVEL_CONSTANT_BOTTOM = "level_constant_bottom"

# SCALE ID
SCALE_MEASURING = "scale_measuring"

# GPIO Assignment
RELAY_PORT_PUMP_CONSTANT = 1
RELAY_PORT_PUMP_MEASURING = 2
RELAY_PORT_VALVE_MEASURING_FILL = 3
RELAY_PORT_VALVE_MEASURING_DRAIN = 5
RELAY_PORT_VALVE_MEASURING_BYPASS = 4
INPUT_PORT_LEVEL_MEASURING_HIGH = 1
INPUT_PORT_LEVEL_MEASURING_LOW = 2
INPUT_PORT_LEVEL_CONSTANT_LOW = 3
INPUT_PORT_LEVEL_CONSTANT_HIGH = 4
